module.exports = {
  extends: 'lighthouse:default',
  settings: {
    // Lighthouse configuration for Boukii Admin V5
    formFactor: 'desktop',
    throttling: {
      rttMs: 40,
      throughputKbps: 10240,
      cpuSlowdownMultiplier: 1,
      requestLatencyMs: 0,
      downloadThroughputKbps: 0,
      uploadThroughputKbps: 0,
    },
    screenEmulation: {
      mobile: false,
      width: 1350,
      height: 940,
      deviceScaleFactor: 1,
      disabled: false,
    },
    emulatedUserAgent:
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    locale: 'en-US',
    onlyCategories: ['performance', 'accessibility', 'best-practices', 'seo', 'pwa'],
    skipAudits: [
      // Skip audits that don't apply to admin panels
      'canonical',
      'structured-data',
      'robots-txt',
      'hreflang',
    ],
    onlyAudits: null,
  },
  audits: [
    // Custom audits for Angular applications
    'first-contentful-paint',
    'largest-contentful-paint',
    'first-meaningful-paint',
    'speed-index',
    'interactive',
    'total-blocking-time',
    'cumulative-layout-shift',

    // Performance audits
    'render-blocking-resources',
    'unused-css-rules',
    'unused-javascript',
    'efficient-animated-content',
    'uses-optimized-images',
    'uses-webp-images',
    'uses-text-compression',
    'uses-rel-preconnect',
    'uses-rel-preload',
    'uses-http2',
    'uses-long-cache-ttl',
    'dom-size',
    'critical-request-chains',
    'user-timings',
    'bootup-time',
    'mainthread-work-breakdown',
    'font-display',
    'resource-summary',
    'third-party-summary',
    'third-party-facades',
    'largest-contentful-paint-element',
    'layout-shift-elements',
    'uses-passive-event-listeners',
    'no-document-write',
    'uses-http2',
    'uses-rel-preconnect',
    'server-response-time',
    'redirects',
    'image-aspect-ratio',
    'image-size-responsive',
    'preload-fonts',
    'legacy-javascript',

    // Accessibility audits
    'color-contrast',
    'image-alt',
    'label',
    'link-name',
    'button-name',
    'document-title',
    'html-has-lang',
    'html-lang-valid',
    'valid-lang',
    'aria-allowed-attr',
    'aria-command-name',
    'aria-hidden-body',
    'aria-hidden-focus',
    'aria-input-field-name',
    'aria-meter-name',
    'aria-progressbar-name',
    'aria-required-attr',
    'aria-required-children',
    'aria-required-parent',
    'aria-roles',
    'aria-toggle-field-name',
    'aria-tooltip-name',
    'aria-treeitem-name',
    'aria-valid-attr-value',
    'aria-valid-attr',
    'bypass',
    'definition-list',
    'dlitem',
    'duplicate-id-active',
    'duplicate-id-aria',
    'form-field-multiple-labels',
    'frame-title',
    'heading-order',
    'list',
    'listitem',
    'meta-refresh',
    'meta-viewport',
    'object-alt',
    'tabindex',
    'td-headers-attr',
    'th-has-data-cells',
    'landmark-one-main',
    'focus-traps',
    'focusable-controls',
    'interactive-element-affordance',
    'logical-tab-order',
    'managed-focus',
    'offscreen-content-hidden',
    'use-landmarks',
    'visual-order-follows-dom',

    // Best practices audits
    'appcache-manifest',
    'is-on-https',
    'uses-http2',
    'uses-passive-event-listeners',
    'no-document-write',
    'external-anchors-use-rel-noopener',
    'geolocation-on-start',
    'doctype',
    'no-vulnerable-libraries',
    'js-libraries',
    'notification-on-start',
    'password-inputs-can-be-pasted-into',
    'image-aspect-ratio',
    'image-size-responsive',
    'preload-fonts',
    'charset',

    // SEO audits (relevant for admin panels)
    'document-title',
    'meta-description',
    'http-status-code',
    'link-text',
    'is-crawlable',
    'robots-txt',
    'image-alt',
    'hreflang',
    'canonical',
    'font-size',
    'plugins',
    'tap-targets',
    'structured-data',

    // PWA audits
    'service-worker',
    'works-offline',
    'viewport',
    'without-javascript',
    'first-contentful-paint-3g',
    'load-fast-enough-for-pwa',
    'redirects-http',
    'splash-screen',
    'themed-omnibox',
    'content-width',
    'apple-touch-icon',
    'maskable-icon',
  ],
  categories: {
    performance: {
      title: 'Performance',
      description: 'Metrics that measure the speed and responsiveness of the application',
      auditRefs: [
        { id: 'first-contentful-paint', weight: 10, group: 'metrics' },
        { id: 'largest-contentful-paint', weight: 25, group: 'metrics' },
        { id: 'first-meaningful-paint', weight: 0, group: 'metrics' },
        { id: 'speed-index', weight: 10, group: 'metrics' },
        { id: 'interactive', weight: 10, group: 'metrics' },
        { id: 'total-blocking-time', weight: 30, group: 'metrics' },
        { id: 'cumulative-layout-shift', weight: 15, group: 'metrics' },

        { id: 'render-blocking-resources', weight: 0, group: 'load-opportunities' },
        { id: 'unused-css-rules', weight: 0, group: 'load-opportunities' },
        { id: 'unused-javascript', weight: 0, group: 'load-opportunities' },
        { id: 'uses-optimized-images', weight: 0, group: 'load-opportunities' },
        { id: 'uses-webp-images', weight: 0, group: 'load-opportunities' },
        { id: 'uses-text-compression', weight: 0, group: 'load-opportunities' },
        { id: 'uses-rel-preconnect', weight: 0, group: 'load-opportunities' },
        { id: 'uses-rel-preload', weight: 0, group: 'load-opportunities' },
        { id: 'font-display', weight: 0, group: 'load-opportunities' },
        { id: 'legacy-javascript', weight: 0, group: 'load-opportunities' },

        { id: 'total-byte-weight', weight: 0, group: 'diagnostics' },
        { id: 'uses-long-cache-ttl', weight: 0, group: 'diagnostics' },
        { id: 'dom-size', weight: 0, group: 'diagnostics' },
        { id: 'critical-request-chains', weight: 0, group: 'diagnostics' },
        { id: 'user-timings', weight: 0, group: 'diagnostics' },
        { id: 'bootup-time', weight: 0, group: 'diagnostics' },
        { id: 'mainthread-work-breakdown', weight: 0, group: 'diagnostics' },
        { id: 'font-display', weight: 0, group: 'diagnostics' },
        { id: 'resource-summary', weight: 0, group: 'diagnostics' },
        { id: 'third-party-summary', weight: 0, group: 'diagnostics' },
      ],
    },
  },
  groups: {
    metrics: {
      title: 'Metrics',
    },
    'load-opportunities': {
      title: 'Opportunities',
      description:
        "These suggestions can help your page load faster. They don't directly affect the Performance score.",
    },
    diagnostics: {
      title: 'Diagnostics',
      description:
        "More information about the performance of your application. These don't directly affect the Performance score.",
    },
  },
};
